use rand::Rng;
use uuid::Uuid;

use crate::session::sessions;
use shared::URL_GEN_MAX_RETRIES;

static ADJECTIVES: &[&str] = &[
    "blue", "green", "red", "gold", "silver", "bright", "calm", "cool", "dark", "deep", "fast",
    "free", "grand", "happy", "keen", "light", "lucky", "magic", "neat", "noble", "proud", "quick",
    "quiet", "rapid", "sharp", "smart", "soft", "solid", "swift", "warm", "wild", "wise", "bold",
    "brave", "clear", "crisp", "fresh", "gentle", "glad", "great", "jolly", "kind", "lively",
    "merry", "mighty", "nimble", "peppy", "plucky", "radiant", "sunny", "vivid", "zesty", "amber",
    "azure", "coral", "crystal", "daring", "eager", "fancy", "golden", "hazy", "ivory", "jade",
    "lunar", "misty", "ocean", "pearl", "royal", "rusty", "sandy", "snowy", "stellar", "tidal",
    "velvet", "violet", "amber", "bronze", "copper", "dusky", "frosty", "glossy", "harbor",
    "indigo", "marble", "mossy", "opal", "plum", "ruby", "sage", "scarlet", "silken", "smoky",
    "spry", "stormy", "sunny", "teal", "tender", "topaz", "twilight", "umber", "vibrant", "wavy",
    "whisper", "winter", "wooden", "young", "zany", "zeal", "zen", "zippy", "active", "agile",
    "alert", "alive", "ample", "arcane", "arctic", "astral", "atomic", "autumn", "balmy", "basic",
    "bliss", "breezy", "busy", "casual", "cheer", "chill", "civic", "classy", "clean", "clever",
    "coastal", "cosmic", "cozy", "curious", "daily", "dandy", "dreamy", "early", "earthy", "easy",
    "electric", "elite", "epic", "eternal", "even", "fair", "famous", "feisty", "fierce", "fine",
    "floral", "fluent", "formal", "frank", "funny", "future", "gentle", "giant", "global", "gloss",
    "grace", "gritty", "handy", "heroic", "honest", "humble", "ideal", "inner", "iron", "jazzy",
    "joyful", "just", "keen", "key", "known", "laced", "lean", "legal", "level", "lofty", "loyal",
    "lucky", "lunar", "lush", "major", "maple", "marvel", "mellow", "metro", "micro", "mild",
    "mint", "modern", "modest", "moral", "motor", "native", "naval", "neat", "new", "nice",
    "nifty", "noble", "normal", "noted", "novel", "ocean", "odd", "olive", "open", "optimal",
    "orange", "organic", "outer", "oval", "pacific", "pale", "pastel",
];

static NOUNS: &[&str] = &[
    "cat",
    "dog",
    "fox",
    "owl",
    "bear",
    "wolf",
    "lion",
    "tiger",
    "eagle",
    "hawk",
    "river",
    "lake",
    "ocean",
    "cloud",
    "star",
    "moon",
    "sun",
    "storm",
    "wind",
    "rain",
    "tree",
    "leaf",
    "fern",
    "pine",
    "oak",
    "maple",
    "cedar",
    "birch",
    "willow",
    "bamboo",
    "stone",
    "rock",
    "peak",
    "hill",
    "cave",
    "cliff",
    "dune",
    "marsh",
    "field",
    "meadow",
    "bridge",
    "tower",
    "castle",
    "harbor",
    "port",
    "dock",
    "gate",
    "path",
    "road",
    "trail",
    "spark",
    "flame",
    "ember",
    "comet",
    "nova",
    "orbit",
    "pulse",
    "wave",
    "beam",
    "ray",
    "falcon",
    "raven",
    "heron",
    "crane",
    "finch",
    "robin",
    "sparrow",
    "wren",
    "lark",
    "swift",
    "badger",
    "beaver",
    "otter",
    "seal",
    "whale",
    "shark",
    "dolphin",
    "turtle",
    "crab",
    "lobster",
    "dragon",
    "phoenix",
    "griffin",
    "unicorn",
    "sphinx",
    "titan",
    "nymph",
    "sprite",
    "fairy",
    "giant",
    "apple",
    "berry",
    "cherry",
    "grape",
    "lemon",
    "mango",
    "melon",
    "peach",
    "plum",
    "citrus",
    "anchor",
    "arrow",
    "blade",
    "crown",
    "shield",
    "sword",
    "hammer",
    "anvil",
    "forge",
    "gear",
    "pixel",
    "node",
    "byte",
    "chip",
    "core",
    "link",
    "port",
    "socket",
    "frame",
    "packet",
    "atlas",
    "compass",
    "beacon",
    "signal",
    "beacon",
    "prism",
    "mirror",
    "lens",
    "scope",
    "chart",
    "canyon",
    "valley",
    "forest",
    "grove",
    "garden",
    "orchard",
    "prairie",
    "tundra",
    "desert",
    "island",
    "crystal",
    "diamond",
    "pearl",
    "ruby",
    "sapphire",
    "topaz",
    "amber",
    "jade",
    "opal",
    "quartz",
    "falcon",
    "panther",
    "jaguar",
    "cougar",
    "lynx",
    "bobcat",
    "cheetah",
    "leopard",
    "puma",
    "hyena",
    "rocket",
    "satellite",
    "shuttle",
    "capsule",
    "module",
    "station",
    "probe",
    "rover",
    "drone",
    "glider",
    "falcon",
    "kestrel",
    "osprey",
    "condor",
    "vulture",
    "pelican",
    "gull",
    "tern",
    "petrel",
    "albatross",
    "badger",
    "mole",
    "rabbit",
    "hare",
    "deer",
    "elk",
    "moose",
    "bison",
    "yak",
    "goat",
    "coral",
    "reef",
    "kelp",
    "shell",
    "pebble",
    "boulder",
    "glacier",
    "iceberg",
    "geyser",
    "spring",
    "falcon",
    "oracle",
    "cipher",
    "token",
    "vault",
    "relay",
    "tunnel",
    "portal",
    "gateway",
    "bridge",
    "falcon",
    "vector",
    "matrix",
    "tensor",
    "scalar",
    "signal",
    "pulse",
    "beacon",
    "anchor",
    "harbor",
    "falcon",
    "circuit",
    "module",
    "kernel",
    "daemon",
    "thread",
    "buffer",
    "cache",
    "queue",
    "stack",
    "falcon",
    "nebula",
    "quasar",
    "pulsar",
    "meteor",
    "asteroid",
    "planet",
    "galaxy",
    "cosmos",
    "void",
    "falcon",
    "summit",
    "ridge",
    "basin",
    "delta",
    "estuary",
    "lagoon",
    "inlet",
    "cove",
    "bay",
    "falcon",
    "falcon",
    "falcon",
    "falcon",
    "falcon",
    "falcon",
    "falcon",
    "falcon",
    "falcon",
    "falcon",
];

pub fn generate_subdomain() -> String {
    let mut rng = rand::rng();
    for _ in 0..URL_GEN_MAX_RETRIES {
        let adj = ADJECTIVES[rng.random_range(0..ADJECTIVES.len())];
        let noun = NOUNS[rng.random_range(0..NOUNS.len())];
        let num = rng.random_range(10..100);
        let subdomain = format!("{adj}-{noun}-{num}");
        if !sessions().contains_key(&subdomain) {
            return subdomain;
        }
    }
    // Fallback with uuid suffix if collisions persist
    let adj = ADJECTIVES[rng.random_range(0..ADJECTIVES.len())];
    let noun = NOUNS[rng.random_range(0..NOUNS.len())];
    let suffix = &Uuid::new_v4().to_string()[..8];
    format!("{adj}-{noun}-{suffix}")
}
